# Generated by Django 3.0.6 on 2020-05-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='time_until_event',
        ),
        migrations.AlterField(
            model_name='event',
            name='published_date',
            field=models.DateField(),
        ),
    ]
